### ISSUE TITLE
Use environment variables for environment specific values defined in settings.py

### ISSUE THREAD

**Issue by martsberger** [NorthBridge/alliance-community#20] opened 2015-09-25 01:29 UTC
Any setting defined in settings.py that could vary depending on environment or should not be in the repo (because it's not public) should be read from an environment variable (`os.environ.get('some_env_variable')`).

This is partly to satisfy how Heroku would like the project set up.

**Comment by hectron** [comment] 2015-09-25 17:05
That's strange. I could've sworn that the settings.py was inheriting from multiple sources -- all which used `os.environ.get('some_variable_from_environment')`. See a2e08fb40fd848d3be8084f569b77e0fde073e43 .

**Comment by martsberger** [comment] 2015-09-25 17:35
The commit you linked has lots of settings variables hard coded that shouldn't be. For example, database connection parameters (https://github.com/NorthBridge/alliance-community/blob/master/alliance/settings.py) should not be hardcoded. Same for the SECRET_KEY.

I would think most of the settings here (https://github.com/NorthBridge/alliance-community/blob/master/alliance/email_settings.py) should not be hardcoded.

This settings file (https://github.com/NorthBridge/alliance-community/blob/master/alliance/backlog/github_settings.py) looks like stuff I wouldn't want in my source control.

Kathy asked me to create this ticket because it Heroku's setup was looking for thing in environment variables. The other reasons to load from environment variables are 
1. Keeps your secrets out of source control (so they aren't shared).
2. Allows local development to change their settings without changing version controlled (shared) files
3. Allows the project to be deployed in different environments (dev, production, somewhere else completely) without changing source files, just changing environment variables.

**Comment by hectron** [comment] 2015-09-25 17:50
Ah, I see.

I thought that you were looking at this file:
https://github.com/NorthBridge/alliance-community/blob/a2e08fb40fd848d3be8084f569b77e0fde073e43/alliance/config/settings/base.py

I think that we should definitely adapt the `os.getenv` pattern for
variables. These should be documented in the setup or at least created in a
`bin/` script. How do you feel about this approach?

Cheers,
h

**Comment by kdflint** [comment] 2015-09-30 01:14
Please refer also to #10 (closed a dupe) for some additional discussion.

**Comment by hectron** [comment] 2015-10-07 03:49
@shacon , can you please verify that there are no hardcoded variables in the codebase? Once confirmed, we can close this issue.

**Comment by kdflint** [comment] 2015-10-22 00:03
This is working in alliance-dev deployment

**Comment by hectron** [comment] 2015-10-23 19:45
@martsberger this can be closed out and marked as resolved.

**Closed by hectron** 2015-10-23 19:45 UTC
Labels: priority 1
